# Generated by Django 3.0.5 on 2021-04-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testparsesuccessinsertfailcrawltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParseRaiseErrorInsertSuccessCrawlTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.testcrawltask',),
        ),
        migrations.CreateModel(
            name='TestParseSuccessInsertBadValueCrawlTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.testcrawltask',),
        ),
        migrations.CreateModel(
            name='TestParseSuccessInsertRaiseErrorCrawlTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.testcrawltask',),
        ),
    ]
