# Generated by Django 3.0.5 on 2021-04-17 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testparseraiseerrorinsertsuccesscrawltask_testparsesuccessinsertbadvaluecrawltask_testparsesuccessin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='url',
            field=models.URLField(default=None, max_length=300, validators=[django.core.validators.URLValidator]),
        ),
    ]
