# Generated by Django 3.0.5 on 2021-04-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210420_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawltask',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='testbasetask',
            old_name='error',
            new_name='error_message',
        ),
    ]
