# Generated by Django 3.0.5 on 2021-05-09 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210420_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lockKey', models.CharField(editable=False, max_length=20, unique=True)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
