# Generated by Django 3.0.5 on 2021-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_databaselock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselock',
            name='lockKey',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
