# Generated by Django 3.0.5 on 2021-04-13 15:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isin', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('canceled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
