# Generated by Django 3.0.5 on 2021-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0002_auto_20210424_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttypedata',
            name='changeLegalToReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='numberBuyLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='numberBuyReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='numberSellReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='numberSellLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='valueBuyLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='valueBuyReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='valueSellLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='valueSellReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='volumeBuyLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='volumeBuyReal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='volumeSellLegal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttypedata',
            name='volumeSellReal',
            field=models.BigIntegerField(),
        ),
    ]
