# Generated by Django 3.0.5 on 2021-04-25 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0005_instrumentstatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TseTmcInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrumentId', models.CharField(max_length=30)),
                ('isin', models.CharField(max_length=20)),
                ('symbolFa', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=50)),
                ('flow', models.SmallIntegerField(choices=[(0, 'عمومی، مشترک بین بورس و فرابورس'), (1, 'بورس'), (2, 'فرابورس'), (3, 'آتی'), (4, 'پایه فرابورس'), (5, 'پایه فرابورس(منتشر نمی شود)'), (6, 'بورس انرژی'), (7, 'بورس کالا')])),
                ('baseVolume', models.BigIntegerField()),
                ('eps', models.IntegerField()),
                ('pe', models.FloatField()),
                ('pe_group', models.FloatField()),
                ('totalShares', models.BigIntegerField()),
                ('cisin', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='tsetmccrawltask',
            old_name='date_to_crawl',
            new_name='dateToCrawl',
        ),
    ]
