# Generated by Django 3.0.5 on 2021-04-25 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0006_auto_20210425_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleDayClientTypeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('instrumentId', models.CharField(max_length=30)),
                ('numberBuyReal', models.BigIntegerField()),
                ('volumeBuyReal', models.BigIntegerField()),
                ('numberBuyLegal', models.BigIntegerField()),
                ('volumeBuyLegal', models.BigIntegerField()),
                ('numberSellReal', models.BigIntegerField()),
                ('volumeSellReal', models.BigIntegerField()),
                ('numberSellLegal', models.BigIntegerField()),
                ('volumeSellLegal', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='clienttypedata',
            name='time',
        ),
    ]
