# Generated by Django 3.0.5 on 2021-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0007_auto_20210425_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderdata',
            name='idShareHolder',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='intratradedata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intratradedata',
            name='instrumentId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='intratradedata',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
