# Generated by Django 3.0.5 on 2021-05-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210509_1526'),
        ('tsetmc', '0007_auto_20210425_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='TseTmcIdentityCertificateCrawlTask',
            fields=[
                ('crawltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CrawlTask')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.crawltask',),
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='baseVolume',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='cisin',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='pe_group',
        ),
        migrations.RemoveField(
            model_name='tsetmcinstrument',
            name='totalShares',
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='Board_code',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='companyEn',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='companyFa',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='industry_code',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='isin_12',
            field=models.CharField(default=123456789123, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='isin_5',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='isin_company_12',
            field=models.CharField(default=12345, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='isin_company_4',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='subIndustry',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='subIndustry_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsetmcinstrument',
            name='symbolFa_30',
            field=models.CharField(default=123456789, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tsetmcinstrument',
            name='symbolFa',
            field=models.CharField(max_length=50),
        ),
    ]
