# Generated by Django 3.0.5 on 2021-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0008_auto_20210512_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetmcidentitycertificatecrawltask',
            name='instrumentId',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
