# Generated by Django 3.0.5 on 2021-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0009_tsetmcidentitycertificatecrawltask_instrumentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsetmcinstrument',
            name='instrumentId',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
