# Generated by Django 3.0.5 on 2021-05-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsetmc', '0010_auto_20210512_1731'),
        ('tsetmc', '0008_auto_20210511_1620'),
    ]

    operations = [
    ]
