# Generated by Django 3.0.5 on 2021-04-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifbinstrument',
            old_name='companyEN',
            new_name='companyEn',
        ),
        migrations.RenameField(
            model_name='ifbinstrument',
            old_name='companyFA',
            new_name='companyFa',
        ),
    ]
