# Generated by Django 3.0.5 on 2021-04-17 14:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0002_auto_20210417_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='paymentDetailsDates',
            field=django_mysql.models.ListTextField(models.CharField(max_length=11), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='paymentDetailsValues',
            field=django_mysql.models.ListTextField(models.CharField(max_length=14), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='profitDistributionDates',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=440, null=True, size=40),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='profitDistributionValues',
            field=django_mysql.models.ListCharField(models.CharField(max_length=12), blank=True, max_length=520, null=True, size=40),
        ),
    ]
