# Generated by Django 3.0.5 on 2021-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0003_auto_20210417_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='isin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
