# Generated by Django 3.0.5 on 2021-04-17 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0004_auto_20210417_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='ifb_url',
            field=models.URLField(max_length=300, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
