# Generated by Django 3.0.5 on 2021-04-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210417_1416'),
        ('ifb', '0005_auto_20210417_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFBCrawlTask',
            fields=[
                ('crawltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CrawlTask')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.crawltask',),
        ),
        migrations.RenameField(
            model_name='ifbinstrument',
            old_name='ifb_url',
            new_name='ifbUrl',
        ),
    ]
