# Generated by Django 3.0.5 on 2021-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0006_auto_20210417_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifbinstrument',
            name='duration',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ifbinstrument',
            name='fbid',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ifbinstrument',
            name='marketMaker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ifbinstrument',
            name='originator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
