# Generated by Django 3.0.5 on 2021-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0007_auto_20210418_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='fbid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
