# Generated by Django 3.0.5 on 2021-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0008_auto_20210418_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifbinstrument',
            name='trustee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
