# Generated by Django 3.0.5 on 2021-04-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0009_ifbinstrument_trustee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='companyEn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='companyFa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='guarantor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='issuer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='listedCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='profitDistributionAgent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='subIndustry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='totalCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
