# Generated by Django 3.0.5 on 2021-04-22 21:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifb', '0010_auto_20210420_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifbinstrument',
            name='profitDistributionDates',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=1100, null=True, size=100),
        ),
        migrations.AlterField(
            model_name='ifbinstrument',
            name='profitDistributionValues',
            field=django_mysql.models.ListCharField(models.CharField(max_length=12), blank=True, max_length=1300, null=True, size=100),
        ),
    ]
